disabled_rules: # 실행에서 제외할 룰 식별자들
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - orphaned_doc_comment
opt_in_rules: # 일부 룰은 옵트 인 형태로 제공
  - empty_count
  - missing_docs
  # 사용 가능한 모든 룰은 swiftlint rules 명령으로 확인 가능
included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
- AppDelegate.swift
- SdeneDelegate.swift
- Makcha/Sources/Data/DTO # DTO 모델 제외
- Makcha/Sources/Domain/Entity/SubwayInfo.swift # SubwayInfo에 열거형의 한글이름 case들이 있어서 제외
# - Projects/App/Sources # AppDelegate, SceneDelegate는 제외
# - Projects/Data/Sources/DTO

# 설정 가능한 룰은 이 설정 파일에서 커스터마이징 가능
# 경고나 에러 중 하나를 발생시키는 룰은 위반 수준을 설정 가능
force_cast: warning # 암시적으로 지정
force_try:
  severity: warning # 명시적으로 지정
# 경고 및 에러 둘 다 존재하는 룰의 경우 값을 하나만 지정하면 암시적으로 경고 수준에 설정됨
line_length:
  warning: 180
  ignores_comments: true
# 함수 길이 100줄로 제한
function_body_length:
  warning: 100
# 값을 나열해서 암시적으로 양쪽 다 지정할 수 있음
type_body_length:
  - 300 # 경고
  - 400 # 에러
# 둘 다 명시적으로 지정할 수도 있음
file_length:
  warning: 500
  error: 1200
# 네이밍 룰은 경고/에러에 min_length와 max_length를 각각 설정 가능
# 제외할 이름을 설정할 수 있음
type_name:
  min_length: 4 # 경고에만 적용됨
  max_length: # 경고와 에러 둘 다 적용
    warning: 40
    error: 50
  excluded:
    - iPhone # 제외할 문자열 값 사용
  allowed_symbols: ["_"]
identifier_name:
  min_length: # min_length에서
    error: 3 # 에러만 적용
  excluded: # 제외할 문자열 목록 사용
    - id
    - URL
    - url
    - end
    - vm
    - app
    - lhs
    - rhs
    - at
    - acc
    - cur
    - box
    - day
    - top
    - key
    - mid
    - low
    - vc
    - vcs
    - min
    - max
    - epm
    - hex
    - to
    - gap
    - sut # System under test (테스트코드에서 사용)
  allowed_symbols: ["_"]
opt_in_rules:
  - missing_docs
reporter: "xcode" # 보고 유형 (xcode, json, csv, codeclimate, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging),
large_tuple:
    warning: 3
nesting:
    type_level:
        warning: 2
